# Site settings
title: Stratum
email: roger@medicor.se
url: https://registercentrum.github.io
description: "Open APIs in the Stratum platform for quality registers in healthcare."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 3cb6ce
  secondary: ffb948
  secondary-dark: e98300

# Footer settings
footer:
  copyright: Registercentrum Västra Götaland
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/medicorab
  - title: google-plus
    url: https://plus.google.com/u/0/+RogerSalomonsson
  - title: github
    url: http://github.com/medicor

# Postal address (add as many lines as necessary)
address:
  - line: Ålegårdsgatan 240
  - line: 431 50 Mölndal

# Credits content
credits: 'Based upon Freelancer theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
