# Site settings
title: Medicor
email: roger@medicor.se
url: https://medicor.github.io
description: "testar Github Pages"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 607D8B
  primary-light: CFD8DC
  secondary: 37474F
  secondary-dark: 263238
  secondary-light: ECEFF1

# Footer settings
footer:
  copyright: Medicor AB
  location:
  social:
  credits:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/medicorab
  - title: google-plus
    url: https://plus.google.com/u/0/+RogerSalomonsson
  - title: github
    url: http://github.com/medicor

# About section - 1st column
about1:
  - line: '<a href="https://www.polymer-project.org/"><img src="/img/logo-polymer.png" style="float: left; margin: 0px 15px 15px 0px"></a>I guess programming still is my main interest, although after a 34 year streak, engagement comes and goes. Polymer and <a href="http://webcomponents.org/>web components</a> has made things a lot more interesting. Polymer also being Google\'s reference implementation of their superb <a href="http://www.google.com/design/spec/material-design/introduction.html">Material Design</a> doesn\'t make it any less interesting. It\'s a paradigm shifter.'

# About section - 1st column
about2:
  - line: '<a href="https://www.ableton.com/en/live"><img src="/img/logo-ableton.png" style="float: left; margin: 0px 15px 15px 0px"></a>Lorem ipsum dolor sit amet, omittam molestie vis no. Vis meis concludaturque an, congue nullam eos ei, facer quaestio eam ea. Ne est nisl mandamus, eam no amet quando malorum, ea ius tale antiopam. Eos in scripta conclusionemque, nec eu porro labitur consequat. Eum ad eleifend necessitatibus, an duo officiis sapientem inciderint.'

about3:
  - line: '<a href="https://www.tradingview.com/chart/eO0kdePX/"><img src="/img/logo-tradingview.png" style="float: left; margin: 0px 15px 15px 0px"></a>Lorem ipsum dolor sit amet, omittam molestie vis no. Vis meis concludaturque an, congue nullam eos ei, facer quaestio eam ea. Ne est nisl mandamus, eam no amet quando malorum, ea ius tale antiopam. Eos in scripta conclusionemque, nec eu porro labitur consequat. Eum ad eleifend necessitatibus, an duo officiis sapientem inciderint.'

# Postal address (add as many lines as necessary)
address:
  - line: Medicor AB 
  - line: roger@medicor.se

# Credits content
credits: 'Tema baserat på <a href="https://github.com/jeromelachaud/freelancer-theme">Freelancer</a> för Jekyll' #  som är skapat av <a href="http://startbootstrap.com">Start Bootstrap</a>

markdown: redcarpet
highlighter: pygments

#redcarpet:
#  extensions: []

#kramdown:
#  input: GFM
