# Site settings
title: Medicor
email: roger@medicor.se
url: https://medicor.github.io
description: "programming, music, trading, ..."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 607D8B
  primary-light: CFD8DC
  secondary: 37474F
  secondary-dark: 263238
  secondary-light: ECEFF1

# Footer settings
footer:
  copyright: Medicor AB
  location:
  social:
  credits:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/medicorab
  - title: google-plus
    url: https://plus.google.com/u/0/+RogerSalomonsson
  - title: github
    url: http://github.com/medicor

# Postal address (add as many lines as necessary)
address:
  - line: Medicor AB 
  - line: Roger Salomonsson
  - line: roger@medicor.se

# Credits content
credits: 'Theme based on<br><a href="https://github.com/jeromelachaud/freelancer-theme">Freelancer for Bootstrap</a><br>theme for <a href="https://jekyllrb.com/">Jekyll</a>'

markdown: redcarpet
highlighter: pygments

#redcarpet:
#  extensions: []

#kramdown:
#  input: GFM
#  parse_block_html: true