# Site settings
title: Medicor
email: roger@medicor.se
url: https://medicor.github.io
description: "testar Github Pages"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 37474F
  secondary: 607D8B
  secondary-dark: 263238

# Footer settings
footer:
  copyright: Medicor AB
  location:
  social:
  credits:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/medicorab
  - title: google-plus
    url: https://plus.google.com/u/0/+RogerSalomonsson
  - title: github
    url: http://github.com/medicor

# Postal address (add as many lines as necessary)
address:
  - line: Medicor AB 
  - line: 431 50 Mölndal
  - line: info@medicor.se

# Credits content
credits: 'Tema baserat på <a href="https://github.com/jeromelachaud/freelancer-theme">Freelancer</a> för Jekyll' #  som är skapat av <a href="http://startbootstrap.com">Start Bootstrap</a>

markdown: redcarpet
highlighter: pygments

#redcarpet:
#  extensions: []

#kramdown:
#  input: GFM
