# Site settings
title: Stratum
email: roger.salomonsson@registercentrum.se
url: https://registercentrum.github.io
description: "plattform för kvalitetsregister inom hälso- och sjukvård"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ffb948
  secondary: 5fd2ea
  secondary-dark: 3cb6ce

# Footer settings
footer:
  copyright: Registercentrum Västra Götaland
  location: Hitta oss
  social: Socialt
  credits: Tack!

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/medicorab
  - title: google-plus
    url: https://plus.google.com/u/0/+RogerSalomonsson
  - title: github
    url: http://github.com/medicor

# Postal address (add as many lines as necessary)
address:
  - line: Registercentrum Västra Götaland 
  - line: 413 45 Göteborg
  - line: info@registercentrum.se

# Credits content
credits: 'Baserat på <a href="http://https://github.com/jeromelachaud/freelancer-theme">Freelancer</a> för Jekyll, skapat av <a href="http://startbootstrap.com">Start Bootstrap</a>'

# Build settings
markdown: kramdown
permalink: pretty
